name: "Build and publish to Docker Hub"
on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.GIT_SSH_KEY }}
    - name: "Publish to Docker Hub"
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: barkbork/evo-scoreboard-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"
        tag_semver: true
